import json

with open("/grade/results/results.json", "r+") as f:
    results = json.load(f)

print(results)

with open("/grade/student/foo.c", "r") as f:
    generated_code = f.read()

results["message"] = f"""The code generated by the AI, based on your prompt is as follows.

{generated_code}
"""

with open("/grade/results/results.json", "w") as f:
    json.dump(results, f)
